<?php

namespace Doctrine\Bundle\DoctrineBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProfilerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Doctrine\Bundle\DoctrineBundle\Controller\ProfilerController();
        return $instance;
    }
}
