<?php

namespace Dunglas\TodoMVCBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TodoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Dunglas\TodoMVCBundle\Controller\TodoController();
        return $instance;
    }
}
