<?php

namespace FOS\RestBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FOSRestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FOS\RestBundle\Controller\FOSRestController();
        return $instance;
    }
}
